[project]
name = "funky-sdk"
version = "0.1.1"
description = "SDK for connecting a Funky workspace to agents"
readme = "README.md"
authors = [
    { name = "JasonJin", email = "jason@funky.dev" }
]
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "twine>=6.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/funky"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
